name: lerobot-libero
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ffmpeg
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch==2.11.0+cu128
      - torchvision==0.26.0+cu128
      - lerobot[libero]==0.6.1
